const state={lang:localStorage.getItem("eh-lang")||"zh",era:3,filter:"all",playing:false,textScale:Number(localStorage.getItem("eh-scale")||1)};
const copy={
zh:{navExplore:"探索",navAtlas:"植物图鉴",navJourneys:"旅程",navStories:"故事",navEvidence:"证据与安全",start:"开始疗愈之旅",heroKicker:"A GLOBAL ATLAS OF NATURE, CULTURE & HEALING",heroTitle:"与自然同行，沿着时间读懂人类的疗愈故事",heroLead:"不需要先懂中医、草药、芳香、冥想或传统医学。选一个地方，滑过年代，点开一个故事。",exploreMap:"探索动态世界地图",surprise:"随便带我看看",heroNoteTitle:"同一个地球，不同文明，不同年代",heroNoteText:"植物、药房、浴疗、声音、身体、仪式与现代证据，在地图上重新连起来。",featured:"精选故事",heroStoryTitle:"普罗旺斯：一朵花如何改变一个地方的生活方式",heroStoryText:"玫瑰、薰衣草、香草园、蒸馏器、药房、香水与慢生活——先从一个好看的故事进入，再慢慢展开历史与知识。",openStory:"展开 Story →",plants:"植物",aroma:"芳香",water:"水疗",sound:"声音",body:"身体",animals:"动物",ritual:"仪式",worldMap:"世界地图",dynamicMap:"DYNAMIC WORLD HEALING MAP",mapTitle:"地图不是静态背景，它会跟着年代改变",mapSub:"拖动时间轴，地图上的节点、路线和右侧故事都会换成那个年代真正应该出现的内容。",filterTitle:"探索地区与方式",all:"全部",currentEra:"当前年代",playTime:"播放时间",mapHint:"点一个节点，看这个年代的故事",timelineCaption:"穿越时间的疗愈地图",storiesInEra:"此刻的故事",featuredJourneys:"FEATURED JOURNEYS",journeyTitle:"整理得最好的内容，先做成一条条好看的旅程",journeySub:"数据库继续扩大，但首页只放已经足够美、足够清楚、适合小白进入的内容。",storyModeTitle:"先让你“看懂”，再决定要不要深挖",storyModeLead:"每个 Story 都从六个问题开始：我们在哪里？现在是什么年代？眼前是什么？当时的人怎么理解？后来发生了什么？今天我们知道什么？",q1:"我们在哪里？",q2:"现在是什么年代？",q3:"眼前是什么？",q4:"当时怎么理解？",q5:"后来发生了什么？",q6:"今天我们知道什么？",goodThings:"Good things grow slowly.",atlasTitle:"植物与香气图鉴",atlasSub:"每张卡先给一句人话，再展开分布、历史、传统用途、现代研究、安全和相关故事。",evidenceTitle:"传统怎么说，与现代证据到哪一步，分开看",evidenceText:"Earth Healing 会保存古籍、民间、灵性和活态传统，但不会把它们自动写成现代医学事实。所有内容都可以继续展开来源、证据等级、安全提示与文化语境。",traditionalRecord:"传统记录",modernEvidence:"现代证据",safety:"安全提示",sources:"来源"},
en:{navExplore:"Explore",navAtlas:"Plant Atlas",navJourneys:"Journeys",navStories:"Stories",navEvidence:"Evidence & Safety",start:"Begin Your Journey",heroKicker:"A GLOBAL ATLAS OF NATURE, CULTURE & HEALING",heroTitle:"Travel through time to understand how people have cared, healed and lived with nature",heroLead:"You do not need to know TCM, herbs, aromatherapy, meditation or traditional medicine first. Pick a place, move through time, open a story.",exploreMap:"Explore the Dynamic World Map",surprise:"Surprise Me",heroNoteTitle:"One Earth, many cultures, many eras",heroNoteText:"Plants, pharmacies, bathing, sound, body practices, ritual and modern evidence reconnect on one map.",featured:"FEATURED STORY",heroStoryTitle:"Provence: how flowers changed the way a place lived",heroStoryText:"Roses, lavender, herb gardens, stills, apothecaries, perfume and slow living — begin with a beautiful story, then unfold the history and knowledge.",openStory:"Open Story →",plants:"Plants",aroma:"Aroma",water:"Water",sound:"Sound",body:"Body",animals:"Animals",ritual:"Ritual",worldMap:"World Map",dynamicMap:"DYNAMIC WORLD HEALING MAP",mapTitle:"The map is not a backdrop — it changes with time",mapSub:"Move the timeline and the visible nodes, routes and Story Rail update to match that historical world.",filterTitle:"Explore regions & methods",all:"All",currentEra:"Current era",playTime:"Play Through Time",mapHint:"Tap a node to open a story from this era",timelineCaption:"A healing map through time",storiesInEra:"Stories in this era",featuredJourneys:"FEATURED JOURNEYS",journeyTitle:"The best-curated content becomes a beautiful journey first",journeySub:"The database keeps growing, while the homepage promotes only material that is clear, beautiful and ready for first-time explorers.",storyModeTitle:"Understand first. Go deeper only when you want to.",storyModeLead:"Every Story begins with six questions: Where are we? When is this? What are we looking at? How did people understand it then? What changed next? What do we know today?",q1:"Where are we?",q2:"When is this?",q3:"What are we looking at?",q4:"How was it understood?",q5:"What changed next?",q6:"What do we know today?",goodThings:"Good things grow slowly.",atlasTitle:"Flora & Aroma Atlas",atlasSub:"Every card starts in plain language, then expands into distribution, history, traditional use, modern evidence, safety and related stories.",evidenceTitle:"Traditional claims and modern evidence are shown separately",evidenceText:"Earth Healing preserves historical, folk, spiritual and living traditions without automatically presenting them as biomedical fact. Every topic can expand into sources, evidence level, safety and cultural context.",traditionalRecord:"Traditional record",modernEvidence:"Modern evidence",safety:"Safety",sources:"Sources"}};

const eras=[
{key:"ancient",zh:"史前与古代",en:"Prehistory & Ancient",range:"Before 0",stories:[
{type:"water",x:57,y:44,placeZh:"尼罗河流域",placeEn:"Nile Valley",titleZh:"当水、植物和身体照护进入古代记录",titleEn:"When water, plants and bodily care entered ancient records",hookZh:"先看古人生活中的照护，再看后来的医学体系怎样形成。",hookEn:"Start with care in everyday ancient life, then see how later medical systems formed.",img:"./assets/reference/images/provence_bird_botanical_atlas.webp"},
{type:"ritual",x:67,y:56,placeZh:"南亚",placeEn:"South Asia",titleZh:"植物、吟诵与仪式曾属于同一个世界",titleEn:"Plants, chant and ritual once shared one knowledge world",hookZh:"声音、植物、身体与宇宙秩序并没有被现代学科切开。",hookEn:"Sound, plants, body and cosmology had not yet been divided by modern disciplines.",img:"./assets/reference/images/alishan_healing_adventure.webp"},
{type:"body",x:80,y:45,placeZh:"中国",placeEn:"China",titleZh:"身体如何被放进季节与宇宙秩序里理解",titleEn:"How the body was read through season and cosmology",hookZh:"先理解传统模型，再和现代解剖与证据分开看。",hookEn:"Understand the traditional model first, then view it separately from modern anatomy and evidence.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp"}]},
{key:"classical",zh:"古典时期",en:"Classical",range:"0–500",stories:[
{type:"plant",x:48,y:35,placeZh:"地中海",placeEn:"Mediterranean",titleZh:"一部药物书开始跨越多个世纪",titleEn:"A materia medica text begins a centuries-long journey",hookZh:"植物被画下来、命名、比较，并随着抄写和翻译继续旅行。",hookEn:"Plants were drawn, named, compared and carried forward through copying and translation.",img:"./assets/reference/images/provence_bird_botanical_atlas.webp"},
{type:"water",x:47,y:39,placeZh:"罗马世界",placeEn:"Roman world",titleZh:"浴场不是洗澡间，而是城市生活",titleEn:"Baths were more than places to wash",hookZh:"热、水、建筑和社交一起构成身体照护空间。",hookEn:"Heat, water, architecture and social life formed spaces of bodily care.",img:"./assets/reference/images/provence_perfume_estate.webp"},
{type:"plant",x:80,y:45,placeZh:"中国",placeEn:"China",titleZh:"本草开始形成更稳定的知识体系",titleEn:"Materia medica becomes a more stable knowledge system",hookZh:"药材被命名、分类，并进入长期流传的文本传统。",hookEn:"Medicinal materials were named, classified and organized into enduring texts.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp"}]},
{key:"medieval",zh:"中世纪",en:"Medieval",range:"500–1500",stories:[
{type:"aroma",x:58,y:40,placeZh:"西亚",placeEn:"West Asia",titleZh:"翻译、药房与蒸馏重新连接知识世界",titleEn:"Translation, pharmacy and distillation reconnect knowledge worlds",hookZh:"不同文明的文本、药材和技术在城市网络里相遇。",hookEn:"Texts, materials and techniques from different civilizations met in urban networks.",img:"./assets/reference/images/provence_perfume_estate.webp"},
{type:"plant",x:45,y:30,placeZh:"欧洲",placeEn:"Europe",titleZh:"修道院里的药草园与药房",titleEn:"Herb gardens and apothecaries in monasteries",hookZh:"花园、抄本、药材储藏和照护在同一空间发生。",hookEn:"Gardens, manuscripts, medicine storage and care existed in one setting.",img:"./assets/reference/images/provence_bird_botanical_atlas.webp"},
{type:"plant",x:80,y:45,placeZh:"中国",placeEn:"China",titleZh:"城市药局、方书与药材供应",titleEn:"Urban pharmacies, formularies and medicine supply",hookZh:"知识不只写进书，也进入越来越组织化的城市医疗。",hookEn:"Knowledge lived not only in books but in increasingly organized urban care.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp"}]},
{key:"early",zh:"近代早期",en:"Early Modern",range:"1500–1800",stories:[
{type:"aroma",x:45,y:31,placeZh:"法国 · 普罗旺斯",placeEn:"Provence, France",titleZh:"花园、香草与蒸馏术的黄金时代",titleEn:"Gardens, aromatics and the age of distillation",hookZh:"植物进入香料、药房、蒸馏器与新的生活方式。",hookEn:"Plants entered perfumery, apothecaries, stills and new ways of life.",img:"./assets/reference/images/provence_perfume_estate.webp",video:"./assets/reference/videos/provence_estate_sim.mp4"},
{type:"plant",x:25,y:61,placeZh:"安第斯",placeEn:"Andes",titleZh:"地方植物进入全球医药贸易",titleEn:"Local plants enter global medical trade",hookZh:"植物知识与贸易、帝国、药房和现代药物史交织。",hookEn:"Plant knowledge became entangled with trade, empire, pharmacy and modern drug history.",img:"./assets/reference/images/alishan_healing_adventure.webp"},
{type:"plant",x:85,y:45,placeZh:"日本",placeEn:"Japan",titleZh:"汉方与本草学在日本重新整理知识",titleEn:"Kampo and honzogaku reorganize medical knowledge in Japan",hookZh:"外来传统、本土植物研究与日常医疗逐渐形成自己的路径。",hookEn:"Imported traditions, local plant study and everyday care developed their own path.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp"}]},
{key:"modern",zh:"现代",en:"Modern",range:"1800–2000",stories:[
{type:"water",x:45,y:28,placeZh:"欧洲",placeEn:"Europe",titleZh:"温泉小镇变成近代健康旅行目的地",titleEn:"Spa towns become modern health destinations",hookZh:"水疗进入疗养地、酒店、诊所与近代旅游。",hookEn:"Hydrotherapy entered resorts, hotels, clinics and modern travel.",img:"./assets/reference/images/provence_perfume_estate.webp"},
{type:"aroma",x:44,y:31,placeZh:"法国",placeEn:"France",titleZh:"现代芳香疗法与精油文化成形",titleEn:"Modern aromatherapy and essential-oil culture take shape",hookZh:"蒸馏香料、药房文化与现代健康消费逐渐汇合。",hookEn:"Distilled aromatics, pharmacy culture and modern wellness consumption converged.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp",video:"./assets/reference/videos/perfume_lab_tutorial.mp4"},
{type:"body",x:17,y:29,placeZh:"北美",placeEn:"North America",titleZh:"音乐、园艺与动物辅助逐渐专业化",titleEn:"Music, horticulture and animal-assisted fields professionalize",hookZh:"一些分散的照护方式逐步形成现代专业领域。",hookEn:"Several dispersed care practices became modern professional fields.",img:"./assets/reference/images/alishan_healing_adventure.webp"}]},
{key:"today",zh:"当代",en:"Today",range:"2000+",stories:[
{type:"plant",x:66,y:57,placeZh:"全球",placeEn:"Global",titleZh:"传统疗愈进入证据、安全与监管时代",titleEn:"Traditional healing enters the era of evidence, safety and regulation",hookZh:"今天还要问：证据到哪一步？风险是什么？谁有资格实践？",hookEn:"Today we also ask: What is the evidence? What are the risks? Who is qualified to practice?",img:"./assets/reference/images/provence_bird_botanical_atlas.webp"},
{type:"sound",x:56,y:43,placeZh:"全球",placeEn:"Global",titleZh:"“声音疗愈”被拆成不同层次",titleEn:"“Sound healing” is separated into distinct layers",hookZh:"声学、音乐治疗、吟唱、振动声学和形而上“频率”不再混成一个概念。",hookEn:"Acoustics, music therapy, chant, vibroacoustics and metaphysical frequency claims are no longer collapsed together.",img:"./assets/reference/images/alishan_healing_adventure.webp"},
{type:"ritual",x:79,y:46,placeZh:"全球",placeEn:"Global",titleZh:"活态传统如何被尊重地数字化",titleEn:"How living traditions can be digitized respectfully",hookZh:"公开知识、社区语境与神圣/私密知识必须有不同访问层级。",hookEn:"Public knowledge, community context and sacred/private knowledge require different access levels.",img:"./assets/reference/images/butterfly_perfume_estate_infographic.webp"}]}
];

const featuredFallback={
journeys:[
{id:"journey-provence",title_zh:"普罗旺斯：花园、香气与蒸馏",title_en:"Provence: Gardens, Scent & Distillation",place_zh:"法国 · 普罗旺斯",place_en:"Provence, France",era_zh:"近代早期 → 当代",era_en:"Early Modern → Today",theme:"aroma",image:"assets/reference/images/provence_perfume_estate.webp",hook_zh:"从玫瑰、薰衣草与香草园开始，看植物如何进入蒸馏器、药房、香水产业与今天的芳香文化。",hook_en:"Start with roses, lavender and aromatic gardens, then follow plants into stills, apothecaries, perfumery and modern aroma culture."},
{id:"journey-yao-bath",title_zh:"广西瑶浴：一桶热水里的植物世界",title_en:"Yao Medicinal Bathing: A Botanical World in Hot Water",place_zh:"中国 · 广西",place_en:"Guangxi, China",era_zh:"活态传统",era_en:"Living Tradition",theme:"water",image:"assets/reference/images/alishan_healing_adventure.webp",hook_zh:"先看一眼“瑶浴到底是什么”，再展开植物、家庭实践、民族医药语境、安全与现代研究。",hook_en:"First understand what Yao medicinal bathing is, then unfold plants, household practice, ethnomedical context, safety and modern research."},
{id:"journey-ayurveda",title_zh:"印度：从日常起居走进 Ayurveda",title_en:"India: Entering Ayurveda Through Everyday Life",place_zh:"印度",place_en:"India",era_zh:"古典传统 → 当代",era_en:"Classical Traditions → Today",theme:"body",image:"assets/reference/images/butterfly_perfume_estate_infographic.webp",hook_zh:"不先背 Dosha。先看人们怎样安排饮食、油浴、植物、呼吸和一天的节奏。",hook_en:"No need to memorize doshas first. See how food, oil massage, plants, breath and daily rhythm fit together."},
{id:"journey-sound",title_zh:"世界声音疗愈：同一个词下的不同世界",title_en:"Sound & Healing: Different Worlds Under One Label",place_zh:"全球",place_en:"Global",era_zh:"古代 → 当代",era_en:"Ancient → Today",theme:"sound",image:"assets/reference/images/alishan_healing_adventure.webp",hook_zh:"吟唱、音乐治疗、鼓、颂钵、振动声学和“频率疗愈”并不是同一件事。这里把它们一层层拆开。",hook_en:"Chant, music therapy, drums, singing bowls, vibroacoustics and ‘frequency healing’ are not the same thing. Explore them layer by layer."}
],
plants:[
{id:"lavender",zh:"薰衣草",en:"Lavender",latin:"Lavandula angustifolia",theme:"aroma",region_zh:"地中海 / 普罗旺斯",region_en:"Mediterranean / Provence",image:"assets/reference/images/provence_perfume_estate.webp",story_zh:"一朵花如何连接农田、蒸馏、香水、药房和现代芳香文化。",story_en:"How one flower connects fields, distillation, perfumery, pharmacy and modern aroma culture."},
{id:"rose",zh:"玫瑰",en:"Rose",latin:"Rosa spp.",theme:"aroma",region_zh:"西亚 / 欧洲 / 全球",region_en:"West Asia / Europe / Global",image:"assets/reference/images/provence_bird_botanical_atlas.webp",story_zh:"既是花园植物，也是香材、纯露与文化象征。",story_en:"A garden flower, aromatic material, hydrosol source and cultural symbol."},
{id:"mugwort",zh:"艾草",en:"Mugwort",latin:"Artemisia argyi",theme:"plant",region_zh:"中国 / 东亚",region_en:"China / East Asia",image:"assets/reference/images/butterfly_perfume_estate_infographic.webp",story_zh:"从端午草束到艾灸与药浴，看同一植物怎样进入不同生活场景。",story_en:"From seasonal herb bundles to moxibustion and bathing, see one plant across many contexts."},
{id:"ginseng",zh:"人参",en:"Ginseng",latin:"Panax ginseng",theme:"plant",region_zh:"东北亚",region_en:"Northeast Asia",image:"assets/reference/images/alishan_healing_adventure.webp",story_zh:"植物、山林、贸易、珍贵药材与现代商品化交织在一起。",story_en:"A story of forests, trade, precious materia medica and modern commercialization."},
{id:"frankincense",zh:"乳香",en:"Frankincense",latin:"Boswellia spp.",theme:"ritual",region_zh:"阿拉伯半岛 / 非洲之角",region_en:"Arabia / Horn of Africa",image:"assets/reference/images/provence_perfume_estate.webp",story_zh:"树脂如何沿贸易路线进入宗教、香气、药房与仪式。",story_en:"How a resin travelled through trade into religion, scent, pharmacy and ritual."},
{id:"turmeric",zh:"姜黄",en:"Turmeric",latin:"Curcuma longa",theme:"plant",region_zh:"南亚",region_en:"South Asia",image:"assets/reference/images/butterfly_perfume_estate_infographic.webp",story_zh:"厨房、染色、传统医药与现代研究围绕同一种根茎展开。",story_en:"Kitchen, dye, traditional medicine and modern research meet around one rhizome."}
]};

let featured=featuredFallback;
fetch("./data/site_featured_content_v1.json").then(r=>r.ok?r.json():Promise.reject()).then(d=>{featured=d;renderJourneys();renderPlants();}).catch(()=>{renderJourneys();renderPlants();});

function tr(k){return copy[state.lang][k]||k}
function applyLanguage(){
  document.documentElement.lang=state.lang==="zh"?"zh-CN":"en";
  document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(copy[state.lang][k]) el.textContent=copy[state.lang][k]});
  document.getElementById("heroSearch").placeholder=state.lang==="zh"?"搜索植物、地点、疗愈方式…":"Search plants, places, practices…";
  renderEra();renderJourneys();renderPlants();
}
function currentStories(){return eras[state.era].stories.filter(s=>state.filter==="all"||s.type===state.filter)}
function renderEra(){
  const e=eras[state.era];
  document.getElementById("eraTitle").textContent=(state.lang==="zh"?e.zh:e.en)+" · "+e.range;
  document.getElementById("timeCaptionEra").textContent=e.en;
  document.getElementById("storyEraLabel").textContent=state.lang==="zh"?e.zh:e.en;
  document.getElementById("timeSlider").value=state.era;
  document.querySelectorAll(".time-label").forEach((n,i)=>n.classList.toggle("active",i===state.era));
  renderMarkers();renderStories();
}
function buildTimeLabels(){
  const el=document.getElementById("timeLabels");el.innerHTML="";
  eras.forEach((e,i)=>{const s=document.createElement("span");s.className="time-label"+(i===state.era?" active":"");s.textContent=state.lang==="zh"?e.zh:e.en;el.appendChild(s)})
}
function renderMarkers(){
  const wrap=document.getElementById("markers");wrap.innerHTML="";
  currentStories().forEach(s=>{const b=document.createElement("button");b.className="marker "+s.type;b.style.left=s.x+"%";b.style.top=s.y+"%";b.innerHTML='<span>'+({plant:"❧",aroma:"✿",water:"≈",sound:"♪",body:"◌",ritual:"✧"}[s.type]||"✦")+'</span><span class="tip">'+(state.lang==="zh"?s.placeZh:s.placeEn)+'</span>';b.onclick=()=>openStory(s);wrap.appendChild(b)})
}
function renderStories(){
  const wrap=document.getElementById("storyCards");wrap.innerHTML="";
  const data=currentStories();
  if(!data.length){wrap.innerHTML='<p style="font-size:.72rem;color:#7c696b">'+(state.lang==="zh"?"这个年代没有该筛选下的精选故事。":"No featured story in this filter for this era.")+'</p>';return}
  data.forEach(s=>{const a=document.createElement("article");a.className="story-card";a.innerHTML='<img src="'+s.img+'" alt=""><div class="meta"><span>'+(state.lang==="zh"?s.placeZh:s.placeEn)+'</span><span>'+eras[state.era].range+'</span></div><h3>'+(state.lang==="zh"?s.titleZh:s.titleEn)+'</h3><p>'+(state.lang==="zh"?s.hookZh:s.hookEn)+'</p><div class="read">'+(state.lang==="zh"?"展开故事 →":"Open story →")+'</div>';a.onclick=()=>openStory(s);wrap.appendChild(a)})
}
function renderJourneys(){
  const wrap=document.getElementById("journeyGrid");if(!wrap)return;wrap.innerHTML="";
  (featured.journeys||[]).forEach(j=>{const el=document.createElement("article");el.className="journey";el.dataset.id=j.id;el.innerHTML='<img src="./'+j.image+'" alt=""><div class="content"><div class="j-meta">'+(state.lang==="zh"?j.place_zh:j.place_en)+' · '+(state.lang==="zh"?j.era_zh:j.era_en)+'</div><h3>'+(state.lang==="zh"?j.title_zh:j.title_en)+'</h3><p>'+(state.lang==="zh"?j.hook_zh:j.hook_en)+'</p><div class="j-cta">'+(state.lang==="zh"?"开始这条旅程 →":"Begin this journey →")+'</div></div>';el.onclick=()=>openJourney(j);wrap.appendChild(el)})
}
function renderPlants(){
  const wrap=document.getElementById("plantGrid");if(!wrap)return;wrap.innerHTML="";
  const mode=document.querySelector(".atlas-tab.active")?.dataset.atlas||"all";
  (featured.plants||[]).filter(p=>mode==="all"||p.theme===mode).forEach(p=>{const el=document.createElement("article");el.className="plant-card";el.innerHTML='<div class="plant-image"><img src="./'+p.image+'" alt=""></div><h3>'+(state.lang==="zh"?p.zh:p.en)+'</h3><div class="latin">'+p.latin+'</div><div class="region">'+(state.lang==="zh"?p.region_zh:p.region_en)+'</div><p>'+(state.lang==="zh"?p.story_zh:p.story_en)+'</p><div class="card-link">'+(state.lang==="zh"?"查看图鉴 →":"Open atlas →")+'</div>';el.onclick=()=>openPlant(p);wrap.appendChild(el)})
}
function openStory(s){
  const e=eras[state.era];showDialog({img:s.img,meta:(state.lang==="zh"?s.placeZh:s.placeEn)+" · "+(state.lang==="zh"?e.zh:e.en)+" · "+e.range,title:state.lang==="zh"?s.titleZh:s.titleEn,lead:state.lang==="zh"?s.hookZh:s.hookEn,video:s.video})
}
function openJourney(j){showDialog({img:"./"+j.image,meta:(state.lang==="zh"?j.place_zh:j.place_en)+" · "+(state.lang==="zh"?j.era_zh:j.era_en),title:state.lang==="zh"?j.title_zh:j.title_en,lead:state.lang==="zh"?j.hook_zh:j.hook_en,video:j.video?"./"+j.video:null})}
function openPlant(p){showDialog({img:"./"+p.image,meta:(state.lang==="zh"?p.region_zh:p.region_en)+" · "+p.latin,title:(state.lang==="zh"?p.zh:p.en)+" / "+(state.lang==="zh"?p.en:p.zh),lead:state.lang==="zh"?p.story_zh:p.story_en})}
function showDialog(d){
 const q=state.lang==="zh"?["我们在哪里？","现在是什么年代？","眼前是什么？","当时的人怎么理解、怎么用？","后来发生了什么？","今天我们知道什么？"]:["Where are we?","When is this?","What are we looking at?","How did people understand or use it then?","What changed next?","What do we know today?"];
 const body=document.getElementById("dialogBody");body.innerHTML='<div class="dialog-inner"><img class="dialog-hero" src="'+d.img+'" alt=""><div class="dialog-meta">'+d.meta+'</div><h2>'+d.title+'</h2><p class="dialog-lead">'+d.lead+'</p>'+q.map((x,i)=>'<div class="dialog-block"><b>'+String(i+1).padStart(2,"0")+' · '+x+'</b><p>'+(state.lang==="zh"?"这一层从数据库调取对应地点、年代、人物、植物/器物与来源，用人话先讲清楚。":"This layer pulls the relevant place, era, people, plants/objects and sources from the database, explained in plain language first.")+'</p></div>').join("")+(d.video?'<video controls playsinline style="width:100%;border-radius:18px;margin-top:18px"><source src="'+d.video+'" type="video/mp4"></video>':'')+'<div class="dialog-depth"><div><b>Story</b><br>'+(state.lang==="zh"?"完整故事":"Full story")+'</div><div><b>Evidence</b><br>'+(state.lang==="zh"?"现代证据":"Modern evidence")+'</div><div><b>Safety</b><br>'+(state.lang==="zh"?"安全提示":"Safety")+'</div><div><b>Sources</b><br>'+(state.lang==="zh"?"来源":"Sources")+'</div></div></div>';document.getElementById("storyDialog").showModal()
}
function randomStory(){const era=Math.floor(Math.random()*eras.length);state.era=era;state.filter="all";renderEra();document.getElementById("explore").scrollIntoView({behavior:"smooth"});setTimeout(()=>openStory(eras[era].stories[Math.floor(Math.random()*eras[era].stories.length)]),600)}
buildTimeLabels();applyLanguage();
document.getElementById("langBtn").onclick=()=>{state.lang=state.lang==="zh"?"en":"zh";localStorage.setItem("eh-lang",state.lang);buildTimeLabels();applyLanguage()};
document.getElementById("textSizeBtn").onclick=()=>{state.textScale=state.textScale>=1.2?1:Math.round((state.textScale+.1)*10)/10;document.documentElement.style.setProperty("--font-scale",state.textScale);localStorage.setItem("eh-scale",state.textScale)};
document.documentElement.style.setProperty("--font-scale",state.textScale);
document.getElementById("timeSlider").oninput=e=>{state.era=Number(e.target.value);renderEra()};
document.querySelectorAll(".filter-btn").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll(".filter-btn").forEach(x=>x.classList.toggle("active",x===b));renderEra()});
document.querySelectorAll(".atlas-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".atlas-tab").forEach(x=>x.classList.toggle("active",x===b));renderPlants()});
document.getElementById("surpriseBtn").onclick=randomStory;
document.getElementById("searchBtn").onclick=()=>{const q=document.getElementById("heroSearch").value.trim().toLowerCase();if(!q)return randomStory();const all=[...(featured.plants||[]),...(featured.journeys||[])];const hit=all.find(x=>JSON.stringify(x).toLowerCase().includes(q));if(hit){hit.latin?openPlant(hit):openJourney(hit)}else randomStory()};
document.querySelector("[data-open-feature='journey-provence']").onclick=()=>openJourney((featured.journeys||featuredFallback.journeys)[0]);
document.getElementById("closeDialog").onclick=()=>document.getElementById("storyDialog").close();
document.getElementById("storyDialog").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};
let timer=null;document.getElementById("playBtn").onclick=()=>{if(timer){clearInterval(timer);timer=null;return}timer=setInterval(()=>{state.era=(state.era+1)%eras.length;renderEra()},2200)};
