"""Browser acceptance checks for the deployed static atlas; screenshots are not mockups."""
from __future__ import annotations
import functools, http.server, json, os, pathlib, threading
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
REPORT=ROOT/'site-report'
REPORT.mkdir(exist_ok=True)
class QuietHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
handler=functools.partial(QuietHandler,directory=str(ROOT/'_site'))
server=http.server.ThreadingHTTPServer(('127.0.0.1',8765),handler)
thread=threading.Thread(target=server.serve_forever,daemon=True);thread.start()
base=os.environ.get('SITE_URL','http://127.0.0.1:8765/')
checks=[];errors=[];bad=[]
def check(name,condition):
    checks.append({'check':name,'passed':bool(condition)})
    assert condition,name
try:
  with sync_playwright() as p:
    browser=p.chromium.launch()
    context=browser.new_context(viewport={'width':1440,'height':1000},device_scale_factor=1,locale='zh-CN',reduced_motion='reduce')
    page=context.new_page()
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('response',lambda r:bad.append({'url':r.url,'status':r.status}) if r.status>=400 and r.url.startswith(base) else None)
    response=page.goto(base,wait_until='networkidle',timeout=60000)
    page.wait_for_function('window.EARTH_HEALING_READY === true',timeout=30000)
    check('Homepage HTTP 200',response.status==200)
    state=page.evaluate('window.EARTH_HEALING.state()')
    check('19 published stories, research index kept separate',state['published']==19 and state['research']==500)
    check('Real basemap loaded and interactive',state['mapReady'] and page.locator('.land').count()==1)
    check('All published map points visible initially',page.locator('.pin').count()==19)
    check('Hero artwork decodes in browser',page.evaluate("async()=>{let i=new Image();i.src='./assets/garden.avif';await i.decode();return i.naturalWidth>=900}"))
    check('Desktop has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth+2'))
    page.screenshot(path=str(REPORT/'desktop-home.png'),full_page=False)
    page.locator('#map').scroll_into_view_if_needed()
    page.locator('.explorer-shell').screenshot(path=str(REPORT/'desktop-map.png'))
    page.locator('[data-year="1750"]').click()
    check('Timeline changes visible points to 8 by 1750',page.locator('.pin').count()==8)
    page.locator('[data-year="800"]').click()
    check('Timeline changes visible points to 2 by 800',page.locator('.pin').count()==2)
    page.locator('#clearFilters').click()
    page.locator('#regionFilter').select_option('oceania')
    check('Oceania filter',page.locator('.pin').count()==1)
    page.locator('#clearFilters').click()
    page.locator('[data-theme="animal"]').click()
    check('Animal-assisted filter',page.locator('.pin').count()==1)
    page.locator('#storyRail [data-story]').first.click()
    check('Story expands with substantive text and sources',page.locator('#storyDialog').evaluate('(e)=>e.open') and page.locator('.source-list a').count()>0 and len(page.locator('.story-text').inner_text())>200)
    page.locator('[data-save]').click()
    check('Story bookmark persists',page.locator('[data-save]').get_attribute('aria-pressed')=='true')
    page.keyboard.press('Escape')
    check('Keyboard closes story dialog',not page.locator('#storyDialog').evaluate('(e)=>e.open'))
    page.locator('#clearFilters').click()
    page.locator('#query').fill('Gnawa')
    check('Search filters both map and story rail',page.locator('.pin').count()==1)
    page.locator('#listView').click()
    check('List alternative is available',page.locator('#mapList').is_visible())
    page.locator('#mapView').click()
    page.locator('#clearFilters').click()
    page.locator('#languageToggle').click()
    check('English interface and stories',page.locator('html').get_attribute('lang')=='en' and 'A world of places.' in page.locator('h1').inner_text())
    page.locator('[data-theme="water"]').click()
    check('English thematic filter works',page.locator('.pin').count()==3)
    page.locator('#clearFilters').click()
    page.locator('#playTimeline').click()
    check('Timeline playback starts',page.evaluate('window.EARTH_HEALING.state().playing'))
    first=page.evaluate('window.EARTH_HEALING.state().year');page.wait_for_timeout(1950)
    check('Playback advances chronological anchors',page.evaluate('window.EARTH_HEALING.state().year')!=first)
    page.locator('#playTimeline').click()
    check('Playback pause works',not page.evaluate('window.EARTH_HEALING.state().playing'))
    page.locator('#clearFilters').click()
    page.locator('#includeResearch').check()
    page.locator('#librarySearch').fill('Lavender')
    check('Research index search works without creating fake stories',page.locator('#libraryGrid [data-research]').count()>=1)
    page.locator('#libraryGrid [data-research]').first.click()
    check('Unreviewed record explicitly labelled', 'RESEARCH INDEX' in page.locator('#storyContent').inner_text())
    page.keyboard.press('Escape')
    page.locator('#languageToggle').click()
    page.locator('#includeResearch').uncheck();page.locator('#librarySearch').fill('')
    page.goto(base+'?story=grasse',wait_until='networkidle')
    page.wait_for_function('window.EARTH_HEALING_READY === true')
    check('Shareable deep link opens correct story','格拉斯' in page.locator('#dialogTitle').inner_text())
    page.locator('#storyDialog').screenshot(path=str(REPORT/'desktop-story.png'))
    page.keyboard.press('Escape')
    page.evaluate('scrollTo(0,0)')
    page.screenshot(path=str(REPORT/'desktop-full.png'),full_page=True)
    # Every local video must actually load metadata and decode a frame.
    for video in page.locator('video').all():
      video.evaluate("async v=>{v.muted=true;v.preload='auto';v.load();await new Promise((resolve,reject)=>{v.addEventListener('loadeddata',resolve,{once:true});v.addEventListener('error',()=>reject(new Error('video decode failed')),{once:true});setTimeout(()=>reject(new Error('video load timeout')),15000)});v.pause()}")
    check('Three complete low-resolution concept previews, not corrupted files',page.locator('video').count()==3)
    mobile_context=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,locale='zh-CN',reduced_motion='reduce')
    mobile=mobile_context.new_page();mobile.on('pageerror',lambda e:errors.append(str(e)))
    mobile.goto(base,wait_until='networkidle');mobile.wait_for_function('window.EARTH_HEALING_READY === true')
    check('Mobile has no horizontal page overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth+2'))
    mobile.screenshot(path=str(REPORT/'mobile-home.png'),full_page=False)
    mobile.locator('.explorer-shell').screenshot(path=str(REPORT/'mobile-map.png'))
    mobile.locator('#fontToggle').click()
    check('Large-text mobile layout remains within viewport',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth+2'))
    mobile.locator('#fontToggle').click()
    mobile.locator('#listView').click()
    check('Mobile map content has list navigation',mobile.locator('#mapList').is_visible())
    mobile_context.close()
    check('No JavaScript runtime errors',not errors)
    check('No local HTTP failures',not bad)
    browser.close()
finally:
  server.shutdown()
  (REPORT/'browser-tests.json').write_text(json.dumps({'base_url':base,'checks':checks,'errors':errors,'http_failures':bad},ensure_ascii=False,indent=2),encoding='utf-8')
  print(json.dumps({'checks':checks,'errors':errors,'http_failures':bad},ensure_ascii=False,indent=2))
